apiVersion: v1
entries:
  nlp-insights:
  - apiVersion: v2
    appVersion: 0.0.1
    created: "2022-02-24T14:48:02.04439341Z"
    description: A Helm Chart to deploy the NLP Insights service.
    digest: 0f23831266fa1c80fe75cc2cd8b35bb9325d047ac6470843d8624568ba73f7c7
    home: https://github.com/Alvearie/health-patterns/tree/main/services/nlp-insights
    keywords:
    - ibm
    - alvearie
    - nlp
    - insights
    maintainers:
    - email: atclark@us.ibm.com
      name: Adam T. Clark
    name: nlp-insights
    type: application
    urls:
    - nlp-insights-0.1.0.tgz
    version: 0.1.0
  - apiVersion: v2
    appVersion: 0.0.1
    created: "2022-02-24T14:48:02.044055506Z"
    description: A Helm Chart to deploy the NLP Insights service.
    digest: ba5db4472386bce23d20215dc382a646fa0bd9a4fbf1d04c1166b68f48195d30
    home: https://github.com/Alvearie/health-patterns/tree/main/services/nlp-insights
    keywords:
    - ibm
    - alvearie
    - nlp
    - insights
    maintainers:
    - email: atclark@us.ibm.com
      name: Adam T. Clark
    name: nlp-insights
    type: application
    urls:
    - nlp-insights-0.0.29.tgz
    version: 0.0.29
  - apiVersion: v2
    appVersion: 0.0.1
    created: "2022-02-24T14:48:02.043697901Z"
    description: A Helm Chart to deploy the NLP Insights service.
    digest: c1230dc5a637b7f8089cad138b9112a5e760fe9bda061aacd3267d831ed2bd2f
    home: https://github.com/Alvearie/health-patterns/tree/main/services/nlp-insights
    keywords:
    - ibm
    - alvearie
    - nlp
    - insights
    maintainers:
    - email: atclark@us.ibm.com
      name: Adam T. Clark
    name: nlp-insights
    type: application
    urls:
    - nlp-insights-0.0.28.tgz
    version: 0.0.28
  - apiVersion: v2
    appVersion: 0.0.1
    created: "2022-02-24T14:48:02.038964539Z"
    description: A Helm Chart to deploy the NLP Insights service.
    digest: b496560d207e4f6027ecd0a4537ad8e97f8f7053171f280569f628878dc0be1a
    home: https://github.com/Alvearie/health-patterns/tree/main/services/nlp-insights
    keywords:
    - ibm
    - alvearie
    - nlp
    - insights
    maintainers:
    - email: atclark@us.ibm.com
      name: Adam T. Clark
    name: nlp-insights
    type: application
    urls:
    - nlp-insights-0.0.27.tgz
    version: 0.0.27
  - apiVersion: v2
    appVersion: 0.0.1
    created: "2022-02-24T14:48:02.038644235Z"
    description: A Helm Chart to deploy the NLP Insights service.
    digest: f063afd0f0fc8015c061ddfff83f14102cab18f7f97f0de2d9a0134ded00a141
    home: https://github.com/Alvearie/health-patterns/tree/main/services/nlp-insights
    keywords:
    - ibm
    - alvearie
    - nlp
    - insights
    maintainers:
    - email: atclark@us.ibm.com
      name: Adam T. Clark
    name: nlp-insights
    type: application
    urls:
    - nlp-insights-0.0.26.tgz
    version: 0.0.26
  - apiVersion: v2
    appVersion: 0.0.1
    created: "2022-02-24T14:48:02.03830703Z"
    description: A Helm Chart to deploy the NLP Insights service.
    digest: 1b0b3452b76e7858cbf989a825fec6bf45ce12a8204756a5a4043d6108690b55
    home: https://github.com/Alvearie/health-patterns/tree/main/services/nlp-insights
    keywords:
    - ibm
    - alvearie
    - nlp
    - insights
    maintainers:
    - email: atclark@us.ibm.com
      name: Adam T. Clark
    name: nlp-insights
    type: application
    urls:
    - nlp-insights-0.0.25.tgz
    version: 0.0.25
  - apiVersion: v2
    appVersion: 0.0.1
    created: "2022-02-24T14:48:02.037964126Z"
    description: A Helm Chart to deploy the NLP Insights service.
    digest: d84c82f8520717d6ac718c6969f135197ea70f165054e045ea1e995462e66d41
    home: https://github.com/Alvearie/health-patterns/tree/main/services/nlp-insights
    keywords:
    - ibm
    - alvearie
    - nlp
    - insights
    maintainers:
    - email: atclark@us.ibm.com
      name: Adam T. Clark
    name: nlp-insights
    type: application
    urls:
    - nlp-insights-0.0.24.tgz
    version: 0.0.24
  - apiVersion: v2
    appVersion: 0.0.1
    created: "2022-02-24T14:48:02.037621721Z"
    description: A Helm Chart to deploy the NLP Insights service.
    digest: b48556aefac5fc807b2b6014aa5ab9cd17db6340ee51d761d05fecf587a216e1
    home: https://github.com/Alvearie/health-patterns/tree/main/services/nlp-insights
    keywords:
    - ibm
    - alvearie
    - nlp
    - insights
    maintainers:
    - email: atclark@us.ibm.com
      name: Adam T. Clark
    name: nlp-insights
    type: application
    urls:
    - nlp-insights-0.0.23.tgz
    version: 0.0.23
  - apiVersion: v2
    appVersion: 0.0.1
    created: "2022-02-24T14:48:02.037243917Z"
    description: A Helm Chart to deploy the NLP Insights service.
    digest: c481400dde21587869bc1d3efc9f94f8dbf36de642d829c849588be10e49fbb0
    home: https://github.com/Alvearie/health-patterns/tree/main/services/nlp-insights
    keywords:
    - ibm
    - alvearie
    - nlp
    - insights
    maintainers:
    - email: atclark@us.ibm.com
      name: Adam T. Clark
    name: nlp-insights
    type: application
    urls:
    - nlp-insights-0.0.22.tgz
    version: 0.0.22
  - apiVersion: v2
    appVersion: 0.0.1
    created: "2022-02-24T14:48:02.036909512Z"
    description: A Helm Chart to deploy the NLP Insights service.
    digest: 619348649b94a3ca4098996c9650d104c10a2ede43ee9cd505c6d33fb5b233c5
    home: https://github.com/Alvearie/health-patterns/tree/main/services/nlp-insights
    keywords:
    - ibm
    - alvearie
    - nlp
    - insights
    maintainers:
    - email: atclark@us.ibm.com
      name: Adam T. Clark
    name: nlp-insights
    type: application
    urls:
    - nlp-insights-0.0.21.tgz
    version: 0.0.21
  - apiVersion: v2
    appVersion: 0.0.1
    created: "2022-02-24T14:48:02.036546607Z"
    description: A Helm Chart to deploy the NLP Insights service.
    digest: cab1d51d3af93f0d3bdf53f75a412d4085d0428ae983b7ecc89fa0f86df27ac6
    home: https://github.com/Alvearie/health-patterns/tree/main/services/nlp-insights
    keywords:
    - ibm
    - alvearie
    - nlp
    - insights
    maintainers:
    - email: atclark@us.ibm.com
      name: Adam T. Clark
    name: nlp-insights
    type: application
    urls:
    - nlp-insights-0.0.20.tgz
    version: 0.0.20
  - apiVersion: v2
    appVersion: 0.0.1
    created: "2022-02-24T14:48:02.036130502Z"
    description: A Helm Chart to deploy the NLP Insights service.
    digest: aeeef68415ebf767797f96f6f46c621b38391e8a572cca284d7db3ec3ef01a17
    home: https://github.com/Alvearie/health-patterns/tree/main/services/nlp-insights
    keywords:
    - ibm
    - alvearie
    - nlp
    - insights
    maintainers:
    - email: atclark@us.ibm.com
      name: Adam T. Clark
    name: nlp-insights
    type: application
    urls:
    - nlp-insights-0.0.19.tgz
    version: 0.0.19
  - apiVersion: v2
    appVersion: 0.0.1
    created: "2022-02-24T14:48:02.035798198Z"
    description: A Helm Chart to deploy the NLP Insights service.
    digest: b0bfd6ca37242f18f6ce5938c259274ce7d9be85c3c60a0213fe48e4a1baec81
    home: https://github.com/Alvearie/health-patterns/tree/main/services/nlp-insights
    keywords:
    - ibm
    - alvearie
    - nlp
    - insights
    maintainers:
    - email: atclark@us.ibm.com
      name: Adam T. Clark
    name: nlp-insights
    type: application
    urls:
    - nlp-insights-0.0.18.tgz
    version: 0.0.18
  - apiVersion: v2
    appVersion: 0.0.1
    created: "2022-02-24T14:48:02.035457793Z"
    description: A Helm Chart to deploy the NLP Insights service.
    digest: e9f0c77508d1ab603a00c5087bc3d4cb1965faad2f9d54202aa0ba08b2bc095c
    home: https://github.com/Alvearie/health-patterns/tree/main/services/nlp-insights
    keywords:
    - ibm
    - alvearie
    - nlp
    - insights
    maintainers:
    - email: atclark@us.ibm.com
      name: Adam T. Clark
    name: nlp-insights
    type: application
    urls:
    - nlp-insights-0.0.17.tgz
    version: 0.0.17
  - apiVersion: v2
    appVersion: 0.0.1
    created: "2022-02-24T14:48:02.035110689Z"
    description: A Helm Chart to deploy the NLP Insights service.
    digest: 52b8b48e9867f263c0c11d407691960a9410107c38e79f380504a6a221227fe3
    home: https://github.com/Alvearie/health-patterns/tree/main/services/nlp-insights
    keywords:
    - ibm
    - alvearie
    - nlp
    - insights
    maintainers:
    - email: atclark@us.ibm.com
      name: Adam T. Clark
    name: nlp-insights
    type: application
    urls:
    - nlp-insights-0.0.16.tgz
    version: 0.0.16
  - apiVersion: v2
    appVersion: 0.0.1
    created: "2022-02-24T14:48:02.034216477Z"
    description: A Helm Chart to deploy the NLP Insights service.
    digest: 9e11ce70be79afc77c5eab825462daca2ed9627c49492c48cb1f10caf887f494
    home: https://github.com/Alvearie/health-patterns/tree/main/services/nlp-insights
    keywords:
    - ibm
    - alvearie
    - nlp
    - insights
    maintainers:
    - email: atclark@us.ibm.com
      name: Adam T. Clark
    name: nlp-insights
    type: application
    urls:
    - nlp-insights-0.0.15.tgz
    version: 0.0.15
  - apiVersion: v2
    appVersion: 0.0.1
    created: "2022-02-24T14:48:02.033863872Z"
    description: A Helm Chart to deploy the NLP Insights service.
    digest: b831af9b695ba31a226ed093ad990d70cd30029aa2d6916a9b9d52b80b40f10f
    home: https://github.com/Alvearie/health-patterns/tree/main/services/nlp-insights
    keywords:
    - ibm
    - alvearie
    - nlp
    - insights
    maintainers:
    - email: atclark@us.ibm.com
      name: Adam T. Clark
    name: nlp-insights
    type: application
    urls:
    - nlp-insights-0.0.14.tgz
    version: 0.0.14
  - apiVersion: v2
    appVersion: 0.0.1
    created: "2022-02-24T14:48:02.033514768Z"
    description: A Helm Chart to deploy the NLP Insights service.
    digest: b5e5e260340ef5c2d1c63ae642e9ebabd89a3dc30d6700d8505b4f980a751987
    home: https://github.com/Alvearie/health-patterns/tree/main/services/nlp-insights
    keywords:
    - ibm
    - alvearie
    - nlp
    - insights
    maintainers:
    - email: atclark@us.ibm.com
      name: Adam T. Clark
    name: nlp-insights
    type: application
    urls:
    - nlp-insights-0.0.13.tgz
    version: 0.0.13
  - apiVersion: v2
    appVersion: 0.0.1
    created: "2022-02-24T14:48:02.033154563Z"
    description: A Helm Chart to deploy the NLP Insights service.
    digest: e00a7900d6895b7fe1c5db4e2d74d6711653951740cdaf2d0bbbf8dabd338a9e
    home: https://github.com/Alvearie/health-patterns/tree/main/services/nlp-insights
    keywords:
    - ibm
    - alvearie
    - nlp
    - insights
    maintainers:
    - email: atclark@us.ibm.com
      name: Adam T. Clark
    name: nlp-insights
    type: application
    urls:
    - nlp-insights-0.0.12.tgz
    version: 0.0.12
  - apiVersion: v2
    appVersion: 0.0.1
    created: "2022-02-24T14:48:02.032779858Z"
    description: A Helm Chart to deploy the NLP Insights service.
    digest: 694662e412c61f6df2f27f9ffaa446f66f5e68034955c7778faa056421ca7dee
    home: https://github.com/Alvearie/health-patterns/tree/main/services/nlp-insights
    keywords:
    - ibm
    - alvearie
    - nlp
    - insights
    maintainers:
    - email: atclark@us.ibm.com
      name: Adam T. Clark
    name: nlp-insights
    type: application
    urls:
    - nlp-insights-0.0.11.tgz
    version: 0.0.11
  - apiVersion: v2
    appVersion: 0.0.1
    created: "2022-02-24T14:48:02.032411653Z"
    description: A Helm Chart to deploy the NLP Insights service.
    digest: 47e60fa475e2e33e5e65a142726dbd79d95da0204e40b1739a9ac88945cc5f07
    home: https://github.com/Alvearie/health-patterns/tree/main/services/nlp-insights
    keywords:
    - ibm
    - alvearie
    - nlp
    - insights
    maintainers:
    - email: atclark@us.ibm.com
      name: Adam T. Clark
    name: nlp-insights
    type: application
    urls:
    - nlp-insights-0.0.10.tgz
    version: 0.0.10
generated: "2022-02-24T14:48:02.026403375Z"
