apiVersion: v1
entries:
  nlp-insights:
  - apiVersion: v2
    appVersion: 0.0.1
    created: "2022-02-23T18:44:05.011244818Z"
    description: A Helm Chart to deploy the NLP Insights service.
    digest: 0f23831266fa1c80fe75cc2cd8b35bb9325d047ac6470843d8624568ba73f7c7
    home: https://github.com/Alvearie/health-patterns/tree/main/services/nlp-insights
    keywords:
    - ibm
    - alvearie
    - nlp
    - insights
    maintainers:
    - email: atclark@us.ibm.com
      name: Adam T. Clark
    name: nlp-insights
    type: application
    urls:
    - nlp-insights-0.1.0.tgz
    version: 0.1.0
  - apiVersion: v2
    appVersion: 0.0.1
    created: "2022-02-23T18:44:05.010750722Z"
    description: A Helm Chart to deploy the NLP Insights service.
    digest: 47e60fa475e2e33e5e65a142726dbd79d95da0204e40b1739a9ac88945cc5f07
    home: https://github.com/Alvearie/health-patterns/tree/main/services/nlp-insights
    keywords:
    - ibm
    - alvearie
    - nlp
    - insights
    maintainers:
    - email: atclark@us.ibm.com
      name: Adam T. Clark
    name: nlp-insights
    type: application
    urls:
    - nlp-insights-0.0.10.tgz
    version: 0.0.10
generated: "2022-02-23T18:44:05.009713829Z"
