site_name: NLP Insights
site_description: A Rest service for updating bundles of FHIR resources with discovered insights.
repo_url: https://github.com/LinuxForHealth/nlp-insights
theme:
  name: material
  palette:
    scheme: default
plugins:
  - search:
      separator: '[\s\-\.]+'

copyright: 'Copyright &copy; 2022 IBM Watson Health<br>'

