# This does a Build, Test, Validate on ever push to a user branch
# The idea is that testcase and source code problems are reported 
# early...before a pull request.
#
name: nlp-insights PUSH Validation
on: 
  push:
   branches-ignore:
    - 'main'
   paths-ignore:
    - 'docs/**.md'
defaults:
  run:
    shell: bash

jobs:
  job:
    name: Build nlp-insights
    runs-on: ubuntu-18.04 
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Setup 
      run: |
           sudo apt install python3.9
           sudo update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.9 1
           sudo update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.8 2
           sudo update-alternatives --set python3 /usr/bin/python3.9
           sudo pip3 install -U pip
           npm install -g dockerlint
    - name: Unit Test 
      run: ./gradlew test 

    - name: Static Code Analysis
      run: |
           MESSAGE=$(git log -1 HEAD --pretty=format:%s)
           if [[ "$MESSAGE" == *\[noFailForSourceProblems\]* ]]; then
             CHECK_SOURCE_NO_FAIL="-PnoFailForSourceProblems"
           fi
           ./gradlew checkSource $CHECK_SOURCE_NO_FAIL

    - name: Docker Lint
      run: dockerlint

    - name: Save Artifiacts
      uses: actions/upload-artifact@v2
      with:
        name: nlp-insights-tests
        path: ./build/reports

